### ISSUE TITLE
Add configurable query Nickname

### ISSUE THREAD

**Issue by romanzipp** [Micky5991/laravel-ts3admin#1]
Make Teamspeak Query Nickname configurable.

**src/teamspeak.php#L11**
```php
'nickname' => 'Laravel Webinterface',
```

```php
'nickname' => env('TS_QUERY_NICKNAME', 'Laravel Webinterface'),
```

**Comment by Micky5991** [comment]
The nickname isn't needed to be configurable for every different environment. 

If you want to edit the name, just publish the ServiceProvider with:

```PHP
php artisan vendor:publish --provider=Micky5991\laravel_ts3admin\Providers\TeamspeakServiceProvider
```
The changable teamspeak.php should be under **config/teamspeak.php** now
